name: Docker Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t my-app:latest .
    
    - name: Test Docker container
      run: |
        docker run --rm my-app:latest echo "Container is working!"
    
    - name: List Docker images
      run: docker images